// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    IconBi: exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    IconClarity: timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    IconEosIcons: loading': typeof import('~icons/eos-icons/loading')['default']
    'IconEosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
    IconFa: trash': typeof import('~icons/fa/trash')['default']
    'IconFa:check': typeof import('~icons/fa/check')['default']
    'IconFa:eye': typeof import('~icons/fa/eye')['default']
    'IconFa:list': typeof import('~icons/fa/list')['default']
    'IconFa:listA;t': typeof import('~icons/fa/list-a;t')['default']
    'IconFa:listAlt': typeof import('~icons/fa/list-alt')['default']
    'IconFa:pencil': typeof import('~icons/fa/pencil')['default']
    'IconFa:table': typeof import('~icons/fa/table')['default']
    'IconFa:times': typeof import('~icons/fa/times')['default']
    'IconFa:trash': typeof import('~icons/fa/trash')['default']
    IconFaSolid: ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    IconIc: baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    IconLa: language': typeof import('~icons/la/language')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    IconMdi: githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    IconUil: times': typeof import('~icons/uil/times')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    t: typeof import('~icons/fa/list-a
  }

}
